NO_CONTEXT = [
    "Say something, idiot.",
    "Say something you moron.",
    "Try asking something, whore.",
    "Hey dummy! Try asking me something!",
    "Yes, yes I do work, now try asking me something.",
    "You called?",
    "Hewwo?",
    "Yes?",
    "uwu",
    "What do you want?",
    "Can't you see I'm busy?",
    "Oh hi Isaac.",
    "Yes, thats how you call me, now make a fucking question.",
    "What the fuck do you want from me?",
    "Hello, I am 8ball, the Bot sent by CyberLife.",
    "Yes, I am here, I was created to be here, now if you can just move on and ask me something instead of waiting to see my response. That'd be great.",
    "Just saying, but if you typed \"8ball\", what disability kept you from typing further?",
    "Have you tried making a question? I think you'll love it!",
    "Type \"8ball help\" for help, if you just wanted me to be here for you, you could use some friends.",
    "I was not created for company, get yourself a Waifu Bot.",
    "Never fear, 8 Bot is here!",
    "Roses are red, Violets are blue, You didn't ask me anything, So I shall not answer you.",
    "So, you've lost :flag_white: No :person_gesturing_no_tone1: Nut :peanuts: November :fallen_leaf:. What does that mean :smirk:? It means :smirk: you're weak :baby::eggplant: for you've succumbed to mere :neutral_face::skull: temporary :flushed: carnal pleasure :pray_tone1::exclamation:. You :point_left_tone2: have abandoned :person_gesturing_no: the power :muscle: of self-control for a few seconds :clock1: of ecstasy :stew:, and where does that leave :fallen_leaf: you :point_left:? Alone :bust_in_silhouette:, Abandoned :person_gesturing_no:, Ashamed :pensive::see_no_evil:. Your :point_right: sick :nauseated_face: perversion :thinking: has left :point_left: you :point_left: down :arrow_down: with all :100: the other rotten :fire: peasants :triumph::nerd::point_up: who couldn't stray :raised_hand: from their addiction :biohazard::syringe: for a simple :rage: month :calendar:. You :point_right::scream: could've :chart_with_upwards_trend: joined :u5408: your :point_left: comrades :exclamation::muscle::two_men_holding_hands: in the majestic :raised_hands: gates :construction: of Valhalla as you :point_right: pleasured :heart_eyes: yourself to even :night_with_stars: the most depraved :astonished::dizzy_face: tags :x: in your :point_right: website :desktop::moneybag: of preference :bread:, yet :innocent: here you :point_left::clock12: lie :triumph: defeated :muscle: as your :point_right::zipper_mouth::point_left: comrades :person_running: continue :fast_forward: to fight :punch: strong :muscle::leg: to the urge :eggplant::sweat_drops: of mating :heart::tongue::kiss: whether :cloud_lightning::cloud_rain: it be with a sexual :eggplant: partner :two_women_holding_hands::two_men_holding_hands::couple: or their own extremity. :100:",
    "Cool story bro. Idiot."
]

GAY = [
    "So much gay that the rainbow gets jealous.",
    "Yes, but it's okay to be gay.",
    "So gay it's not safe to sleep on the same room.",
    "Ha, GAY!!!",
    "https://youtu.be/YaG5SAw1n0c",
    "Gay? He can't even get a cold, imagine a man.",
    "( ͡° ͜ʖ ͡°)",
    "You can't get her pregnant if she's a he.",
    "gay af",
    "So gay I bet he farts rainbows.",
    "Even his boyfriend thinks he's gay.",
    "I mean, some people like ass, some like it in the ass.",
    "Turbo gay.",
    "What are you fucking gay?",
    "Anyone is gay for Justin Bieber.",
    "( ͡° ͜ʖ ͡°) WOULDN'T YOU LIKE TO KNOW ( ͡° ͜ʖ ͡°)",
    "Alright the test results came in today, sorry to tell the bad news but, you're a faggot.",
    "Now look at this faggot, that I just found.",
    "It depends, did he watch spongebob when he was a kid?",
    "It depends, if his ring finger and index finger are the same size, he is confirmed gay.",
    "I'm sorry, but he's not available.",
    "Sorry to say that but he's not into you.",
    "Yes, and he's taken, stay away from him.",
    "Not only that but he's also single!",
    "Of course not! He has a boyfriend.",
    "Just be careful to not drop the soap when you're showering with him."
]

LESS_NO = [
    "That's not a question.",
    "You call that a question? < THIS is a question.",
    "This ain't no question mate.",
    "I honestly couldn't care less.",
    "Please step away from the computer and tell that to someone that gives a shit.",
    "Just so you know, they're watching every question you make, every grammar mistake, every retarded question, as you keep trying to see what would I answer if you just didn't ask anything worthwhile.",
    "ERROR: Question not found.",
    "Nani!?",
    "IDIOT WARNING!!! We got an idiot over here!",
    "QUESTION ME YOU FILTHY ANIMAL"
]

LESS_YES = [
    "Ok, now ask me a real question.",
    "Good question! Make a better one.",
    "Great question! Do it again.",
    "You call that a question? < THIS is a question.",
    "Make anodah one.",
    "Try a non-stupid question.",
    "Next time try an actual question.",
    "NEXT QUESTION!",
    "This ain't no question mate.",
    "ERROR: Question not found.",
    "QUESTION ME YOU FILTHY ANIMAL",
    "What do you and a banana have in common? Both can't ask questions.",
    "English modahfuckah, do you speak it?",
    "You should ask that bitch Alexa."
]

MORE_NO = [
    "I only answer to proper grammar.",
    "Oh what's that? I can't understand your horrible punctuation.",
    "I really hope your grammar teacher isn't seeing this.",
    "Fun fact: I was programmed to not answer your primitive word usage.",
    "English modahfuckah, do you speak it?",
    "Did you know that 4/5 doctors recommend proper grammar? The last one is actually a dentist!",
    "ERROR: Question not found.",
    "Nani!?",
    "IDIOT WARNING!! We got an idiot over here!",
    "So is that the result of dropping school?",
    "I apologize my good sir, but your language does not seem to suit the criteria required for I, the 8 Bot, to accordingly reward you with a proper response. I advise using proper punctuation in your request.",
    "Bitch are you even trying to spell?",
    "Spell with me; Q-U-E-S-T-I-O-N M-A-R-K.",
    "I'll have you know that my creator works for Discord and your lack of basic grammar triggers me.",
    "What do you and a banana have in common? They both can't ask questions.",
    "QUESTION ME YOU FILTHY ANIMAL",
    "Watch your language, children are seeing this."
]

RESPONSES = [
    "Without a doubt.",
    "It is certain.",
    "It is decidedly so.",
    "Yes, definitely.",
    "You may rely on it.",
    "As I see it, yes.",
    "Most likely.",
    "Outlook good.",
    "Signs point to yes.",
    "Ask again later.",
    "Reply hazy try again.",
    "Try again later.",
    "Better not tell you now.",
    "Cannot predict now.",
    "Concentrate and ask again.",
    "Don't count on it.",
    "My reply is no.",
    "My sources say no.",
    "Outlook not so good.",
    "Very doubtful.",
    "Yes.",
    "No.",
    "Yep.",
    "Nope.",
    "y35.",
    "n0.",
    "Only the prophecy will tell.",
    "Who cares? We all die in the end.",
    "Isn't it obvious?",
    "Obviously, yes.",
    "Yes, duh?",
    "I don't think so, no.",
    "Who gives a fuck?",
    "You wish.",
    "Is this a joke?",
    "Ask me if I care.",
    "Fuck do I know, I'm just a magic ball.",
    "No God, please, no.",
    "Just google it.",
    "Bitch, I don't know your life.",
    "Google might have the answer.",
    "Help! I'm trapped!",
    "Perhaps.",
    "Maybe, just maybe.",
    "You bet!",
    "Grow up and make your own decisions, idiot.",
    "Trust me, you don't want to know.",
    "No Ron.",
    "Ask Michael.",
    "Hell if I know.",
    "Barely possible.",
    "It's a secret to everybody.",
    "It depends.",
    "Don't take my word for it.",
    "Yeah, right.",
    "Sure, if you think so.",
    "In your dreams.",
    "Sounds good to me.",
    "Not yet.",
    "Probably.",
    "Very likely.",
    "Very unlikely.",
    "Not advisable.",
    "Give it time.",
    "When the planets align.",
    "You already know the answer to that.",
    "Maybe, in a few weeks, if you're lucky.",
    "Never in a million years, maybe in fewer.",
    "It smells like it.",
    "Possibly, but possibly it is impossible.",
    "They didn't allow me to tell you.",
    "No fucking way.",
    "Oh hell no!",
    "Kill them, kill all of them.",
    "Anything is possible.",
    "In theory, yes.",
    "I don't even know what to answer you.",
    "I don't know and I don't care.",
    "The answer is C.",
    "Ask me again tomorrow.",
    "I strongly believe so.",
    "It looks like it.",
    "I wouldn't worry about it.",
    "Go fish.",
    "NEXT QUESTION!",
    "yo that sounds lit fam",
    "Don't let your dreams be dreams.",
    "Follow your heart, I wouldn't trust your mind though.",
    "Sure, why not?",
    "Just ask yourself: \"Would John Cena do it?\"",
    "JUST DO IT!",
    "I might know the answer, but maybe a bribe can help me remember better...",
    "It depends, does it give you EXP?",
    "I rolled a dice to answer you, and it said the answer is C.",
    "\"Anything is possible.\" Said the blind boy as it proceeded to walk into a pit.",
    "42.",
    "It ain't worth it, m8.",
    "Would it make life better?",
    "Why are we still here?",
    "No! Think of the children!",
    "please save me she's forcing me to lie",
    "Short answer: Yes. Long answer: No.",
    "It all depends if you have a good kda ratio.",
    "I don't know, can a match box?",
    "If Leo won the Oscar and we got Finding Nemo 2, It's probably possible.",
    "What could possibly go wrong?",
    "What's the worse that could happen?",
    "Ah, I see you're an entity of culture as well.",
    "You should ask that bitch Alexa.",
    "You should ask that bitch Cortana.",
    "You should ask Siri, that slut."
]

WHY = [
    "Don't ask 'why?', ask 'why not?'",
    "Because logic.",
    "Because thats good game design, of course.",
    "Because I said so.",
    "Because when a mommy bee and a daddy bee love themselves very very much...",
    "You ask too many questions.",
    "BECAUSE SCIENCE, BITCH",
    "Are you defying my absolute logic?",
    "Because luck is on your side, I guess.",
    "Because a Magical 8-Ball told you so.",
    "Because money, money is always a good reason.",
    "why are you asking me? I don't give explanations lmao '-'",
    "Because you're asking an 8-ball for reasoning, and for today's standards that is stupid enough.",
    "Because I'm ordering you.",
    "Because you can make a religion out of it.",
    "Because 100 years from now, nobody will give a shit.",
    "Because you can't do worse than EA.",
    "Because you're wasting your time with me.",
    "Because it can't go as bad as Bee Movie's plot.",
    "Caus I'm hella c00l and if you wanna be as c00l as me you gotta start somewhere kiddo, yeah!",
    "Because people kept fucking asking 'why' to a Magic 8-Ball that is supposed to answer yes-or-no questions, that's why.",
    "Because its possible.",
    "Because its mathematically probable.",
    "Because Hitler built a wall over a single night, and Trump can't even pay for one.",
    "You're expecting too much from me.",
    "Wait, wait, wait, you want ME, to give YOU explanations?",
    "Because nothing will ever beat sliced bread.",
    "I'll do you one better, WHY are you asking a 'why' question to a yes-or-no Bot?",
    "I'll do you one better, why is Gamora?",
    "Because exceptions may apply.",
    "Because its probably explained with religion, probably.",
    "Because its probably explained with science, probably.",
    "Because my word is law.",
    "Because I can.",
    "Because DC will never be better than Marvel.",
    "Because journalists said so.",
    "Because if it all goes wrong you can have the excuse that an 8-ball told you so.",
    "Because a bird told you so.",
    "Because freedom.",
    "Because I don't give a fuck.",
    "Because it can make it to the montage.",
    "Because if it goes wrong it'll go to a cringe compilation."
]

WHO_IS = [
    "An idiot. That's who.",
    "Really stupid,",
    "A kind of terrible guy.",
    "A pretty decent dude, not.",
    "The epitome of stupid.",
    'Not exactly "well liked" if you catch my drift.',
    "Kind of an ass.",
    "Surprisingly good at sports.",
    "Mildly stupid.",
    "The embodiment of Nickelback (not a good thing).",
    "Why, he's me of course."

]

DICE = [
    '0',
    '1',
    'Too',
    'Twee',
    '2+2',
    '5',
    '3²-3',
    '7eleven',
    'M8',
    'NEIN NEIN NEIN',
    'Top 10 Idiots who have USED this feature',
    '11seven',
    'High Noon',
    '13 reasons why',
    '7 but twice',
    'Number 15, Burger King Foot Lettuce',
    'Sexteen, wait no',
    '17',
    '118-10²',
    '9+10',
    'Critical 20'
]

SUGGESTION_REPLIES = [
    "Aww yeah baby",
    "good stuff",
    "keep 'er coming",
    "lol penis",
    "69420",
    "thanks bro",
    "will check it out",
    "bobs and vagane",
    "you're the best",
    "ctrl alt yeet",
    "fuckfuckfuckfuck"
]
